### ISSUE TITLE
Chapter 2 Getting Started is missing content

### ISSUE THREAD

**Issue by niepiekm** [SquareBracketAssociates/PatternsOfDesign#5]
Hi,

I'd like to report a build issue resulting in chapter 2 Getting Started missing its content.
![PatternsOfDesign-missing chapter](https://user-images.githubusercontent.com/6682527/55552792-b6233580-56de-11e9-8d5f-8b1f6369e138.png)

**Comment by Ducasse** [comment]
Thanks. This book is currently under writing.
